In [6]:
import numpy as np

In [7]:
def make_board(x,y):
    return np.zeros((x,y))

In [9]:
make_board(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
test_board = make_board(3,3)

test_board[2,2] = 1
test_board

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [24]:
test_board[0,0] = 1
test_board

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [25]:
test_board = test_board * -1

In [27]:
test_board[0,1] + 1

1.0